name: Generate Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # update setiap 12 jam
  workflow_dispatch:

jobs:
  main-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate main metrics (fast)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.svg
          config_timezone: Asia/Jakarta

          base: header, activity

          plugin_lines: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_gists: yes

          plugins_errors_fatal: no
          optimize: yes

  isocalendar:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Isocalendar full-year
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.isocalendar.svg

          base: ""
          config_timezone: Asia/Jakarta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          optimize: yes

  languages:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Language stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.languages.svg

          base: ""
          config_timezone: Asia/Jakarta

          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_limit: 12
          optimize: yes

  achievements:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          optimize: yes

  habits:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.habits.svg

          base: ""
          config_timezone: Asia/Jakarta

          plugin_habits: yes
          plugin_habits_trim: yes
          plugin_habits_facts: yes
          optimize: yes

  activity:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Recent activity graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.activity.svg

          base: ""
          config_timezone: Asia/Jakarta
          plugin_activity: yes
          plugin_activity_limit: 5
          optimize: yes

  people:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Contributors & followers
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.people.svg

          base: ""
          plugin_people: yes
          plugin_people_types: followers, sponsoring, contributors
          optimize: yes
