name: Generate Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:

  # Main metrics
  main-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate main metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.svg
          config_timezone: Asia/Jakarta

          base: header, activity

          plugin_lines: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_gists: yes

          plugins_errors_fatal: no
          optimize: yes

  # Isocalendar
  isocalendar:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Isocalendar full-year
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.isocalendar.svg

          base: ""
          config_timezone: Asia/Jakarta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          optimize: yes

  # Languages
  languages:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Language stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.languages.svg

          base: ""
          config_timezone: Asia/Jakarta

          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_limit: 12
          optimize: yes

  # LeetCode
  leetcode:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: LeetCode stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.leetcode.svg

          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: Syharipf
          plugin_leetcode_sections: solved, skills, recent
          optimize: yes

  # People
  people:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Contributors & followers
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          filename: metrics.people.svg

          base: ""
          plugin_people: yes
          plugin_people_types: followers, sponsoring, contributors
          optimize: yes
