name: Generate Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # update setiap 12 jam
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate main metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          repo: Syharipf
          filename: metrics.svg
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta
          plugin_lines: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_gists: yes
          plugin_people: yes

      - name: Generate isocalendar full-year
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          repo: Syharipf
          filename: metrics.isocalendar.svg
          base: ""
          config_timezone: Asia/Jakarta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Generate languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          repo: Syharipf
          filename: metrics.languages.svg
          base: ""
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_languages_indepth: no

      - name: Generate achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          repo: Syharipf
          filename: metrics.achievements.svg
          base: ""
          config_timezone: Asia/Jakarta
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

      - name: Generate habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          repo: Syharipf
          filename: metrics.habits.svg
          base: ""
          config_timezone: Asia/Jakarta
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_trim: yes

      - name: Generate recent activity graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          repo: Syharipf
          filename: metrics.activity.svg
          base: ""
          config_timezone: Asia/Jakarta
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_limit: 5

      - name: Generate contributors
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          repo: Syharipf
          filename: metrics.people.svg
          base: ""
          plugin_people: yes
          plugin_people_types: followers, sponsoring, contributors

      - name: Generate repo stargazers
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Syharipf
          repo: Syharipf
          filename: metrics.stars.svg
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 5
